# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json

# toggle_key: ALT
# toggle_key: OFF

# backend: Clipboard

# auto_restart: false

# clipboard_threshold: 100

# max_regex_buffer_size: 30
